# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: PHYS 4480-7680 Computational Physics
author: Erich Mueller
copyright                   : "2025"  # Copyright year to be placed in the footer
logo: logo.png

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - dollarmath
    - amsmath


# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache
#  execute_notebooks: auto

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: P4480.tex
    
# only build files which are loaded into final book
only_build_toc_files: true

# Add a bibtex file so that we can create citations
#bibtex_bibfiles:
#  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/em256/phys4480/ # Online location of your book
  branch: main#master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: false
